### ISSUE TITLE
Is transaction manager thread-safe? 

### ISSUE THREAD

**Issue by yingqiaomxi** [witoldsz/ultm#4]
I am using ULTM with jOOQ for a implement light-weight data service. One question is that, is the TxManager thread-safe? Is it OK if I use it in a multi-thread program?

For example: 
//transaction block
void myHandler(){
txManager.begin()
{
try{
   do-something();
   txManager.commit();
}catch (Exception aException){
  txManager.rollback();
}
}}
In case the myHandler(0 is called by several thread spontaneously, can the TxManager handles this transactions correctly?

**Comment by witoldsz** [comment]
First of all, you do not have to write all this, your example can be reduced to this:
```java
void myHandler() {
  txm.tx(() => do-something());
  // or txm.txResult or other flavors of TxManager.tx… methods
}
```

or if you really want to ignore exceptions:

```java
void myHandler() {
  try {
    txm.tx(() => do-something());
  } catch (Exception e) {
    // ignore (not recommended)
  }
}
```

The `TxManager` can to be used in multiple threads. It is actually designed to do so. The trick is not to mess with threads inside `do-something`, because `TxManager` associates transaction context to threads.

What's a bonus when using ULTM is that it's just few lines of (simple) code, so when in doubt, it is easy to follow what is happening under the hood. I am happy to help in case of doubt.

**Comment by yingqiaomxi** [comment]
In this case, I can use the TxManager as a singleton then...

I have to use tx.commit() or tx.rollback explicitly since, in my case, there are multiple asynchronous operations contained in a transaction. For example, the operations on different tables run in parallel. I use Future for these operations. 

It is difficult to use the implicit transaction management in my case...

**Comment by witoldsz** [comment]
> In this case, I can use the TxManager as a singleton then...

Correct.

> I have to use tx.commit() or tx.rollback explicitly since, in my case, there are multiple asynchronous operations contained in a transaction. For example, the operations on different tables run in parallel. I use Future for these operations.

I am not sure if I get it right, but what `txm.commit/rollback` gives you the `txm.tx` does not in such a case? Do you mean you need sometimes to rollback even though there was no exception? Or you must do something extra before rollback?

Also, you must know that `begin/commit/rollback` works only for the threads they were executed on. If you begin transaction in thread T1 and then do some work on T2 then the T1's `begin` does not "reach" there. ULTM will throw an exception in case you try to talk to database from thread which did not start transaction, but if you work on some kind of thread pool, you can unintentionally fool ULTM, so it won't throw exception, but your code will use transaction context not meant for it, see this: https://github.com/witoldsz/ultm/blob/ee99aed3a924a5270eb80ab0de46502ff1b6f3d2/src/main/java/com/github/witoldsz/ultm/internal/ThreadLocalTxManager.java#L40

**Comment by yingqiaomxi** [comment]
Yes, I did see the IllegalStateException thrown. 

Now, those db operations are run sequentially in the same thread. In the same transaction, after those db operations, I need to call a REST API endpoint with Vertx's asynchronous HttpClient. In the same thread, the Vert.x's asynchronous result handler decides to do tx.commit() or tx.rollback() after receiving the response of the API call. 

It seems that the TxManager throws the IllegalStateExceptionin in this case...

**Comment by yingqiaomxi** [comment]
I have found a way to make the TxManager working in this case. The code of this transaction should run in the same Vertx Context. This made me thinking whether it is worthy of using asynchronous HttpClient. Maybe, Apache synchronous HttpClient would work fine. 

Many thanks for your explanation on how TxManager works!
